RentACar/Controllers/RentalController.cs
using Microsoft.AspNet.Identity;
using RentACar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RentACar.Controllers
{
    public class RentalController : Controller
    {
        DbController dbConnection = new DbController();
        // GET: Rental
      [Authorize]
        public ActionResult Index()
        {
            List<Rental> ListOfRentals = new List<Rental>();
            ListOfRentals = dbConnection.GetRentals();
            string[] arr = User.Identity.GetUserId().Split();
            int Id;
            Int32.TryParse(arr[0],out Id);
            var myRent = ListOfRentals.Where(c => c.Id==Id);
            if (myRent.Count() > 0)
            {
                ViewBag.Shown = true;
            }
            else
                ViewBag.Shown = false;
            ViewBag.Id = Id;
            return View();
        }

        public ActionResult Create()
        {
            var cars = dbConnection.GetCars();
           ViewBag.ListMake =
                new SelectList(dbConnection.GetCars()
                .Select(x => new { value = x.Id, text = x.Make + " " + x.Model + " " + x.Year }).Distinct(),"Value","Text");
         
            

                return View();
        }

      
     
        [HttpPost]
        public ActionResult Confirmation(int? Id, FormCollection form,int? CarId,string CarName, DateTimeOffset StartDate, DateTimeOffset EndDate, string FirstName, string LastName, string  Address, string City,string PostCode, string PhoneNumber)
        {
            //  CarId = (int)ListMake.Where(x => x.Selected).FirstOrDefault();
            double Total = 0, DaysUse;
            DaysUse =(EndDate - StartDate).TotalDays; 
            if (CarName.Equals("Toyota"))
            {
                Total += (22.99 * DaysUse);
            }
            else if (CarName.Equals("Audi"))
            {
                Total += (30 * DaysUse);
            }
            else
                Total = (50 * DaysUse);
            ViewBag.Total = Total;
            ViewBag.DaysUse = DaysUse;
           
            int CarIdd;
             Int32.TryParse(form["ListMake"],out CarIdd);
            CarName = form["CarName"];
            ViewBag.CarName = CarName;
            ViewBag.FirstName = FirstName;
            ViewBag.LastName = LastName;
            
            if (ModelState.IsValid)
            {
                dbConnection.InsertRental(CarIdd, CarName, FirstName, LastName, Address, City, PostCode, PhoneNumber, StartDate, EndDate);
                return View();
            }
            else
                return View("Confirmation");
            //}
         
        }
        // GET: Rental/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Rental/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Rental/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }
        public ActionResult Details(int id)
        {
            List<Rental> ListOfRentals = new List<Rental>();
            ListOfRentals = dbConnection.GetRentals();

            var rentDetails = ListOfRentals.Where(c=>c.Id == id);

            ViewBag.ListOfRent = rentDetails;
            ViewBag.Id = id;
            return View();
        }
        // POST: Rental/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

RentACar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Rent A Car", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "DisplayCars", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("View Cars", "DisplayCars", "Home")</li>

                    @{
                        if (Request.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("MyRentals", "Index/{Id}", "Rental")</li>
 }
                    }
                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Rent A Car</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Content/init.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>